apiVersion: operations.kubeblocks.io/v1
kind: Cluster
metadata:
  name: pg-cluster-restore
  namespace: default
  annotations:
    kubeblocks.io/restore-from-backup: '{"postgresql":{"connectionPassword":"<backup-connection-password>","name":"pg-cluster-backup","namespace":"default","volumeRestorePolicy":"Parallel"}}'
spec:
  # Specifies the behavior when a Cluster is deleted.
  # Valid options are: [DoNotTerminate, Delete, WipeOut] (`Halt` is deprecated since KB 0.9)
  # - `DoNotTerminate`: Prevents deletion of the Cluster. This policy ensures that all resources remain intact.
  # - `Delete`: Extends the `Halt` policy by also removing PVCs, leading to a thorough cleanup while removing all persistent data.
  # - `WipeOut`: An aggressive policy that deletes all Cluster resources, including volume snapshots and backus in external storage. This results in complete data removal and should be used cautiously, primarily in non-production environments to avoid irreversible data loss.
  terminationPolicy: Delete
  # Specifies the name of the ClusterDefinition to use when creating a Cluster.
  clusterDef: postgresql
  # Specifies a list of ClusterComponentSpec objects used to define the
  # individual Components that make up a Cluster.
  # This field allows for detailed configuration of each Component within the
  # Cluster
  componentSpecs:
    - name: postgresql
      serviceVersion: "14.7.2"
      disableExporter: false
      labels:
        # PostgreSQL's CMPD specifies `KUBERNETES_SCOPE_LABEL=apps.kubeblocks.postgres.patroni/scope` through ENVs
        # Te KUBERNETES_SCOPE_LABEL is used to define the label key that Patroni will use to tag Kubernetes resources.
        # This helps Patroni identify which resources belong to the specified scope (or cluster) used to define the label key
        # that Patroni will use to tag Kubernetes resources.
        # This helps Patroni identify which resources belong to the specified scope (or cluster).
        #
        # Note: DO NOT REMOVE THIS LABEL and update the value w.r.t your cluster name
        # the value must follow the format <cluster.metadata.name>-<componentSpecs[].name>
        # which is pg-cluster-postgresql here in this examples
        apps.kubeblocks.postgres.patroni/scope: pg-cluster-restore-postgresql
      # set `replicas` to 2 to create a replication cluster.
      replicas: 1
      resources:
        limits:
          cpu: "0.5"  # Maximum CPU limit for the container
          memory: "0.5Gi"  # Maximum memory limit for the container
        requests:
          cpu: "0.5"  # Minimum CPU requested for the container
          memory: "0.5Gi"  # Minimum memory requested for the container
      volumeClaimTemplates:
        - name: data
          spec:
            # The name of the StorageClass required by the claim.
            # If not specified, the StorageClass annotated with
            # 'storageclass.kubernetes.io/is-default-class-true' will be used by default
            storageClassName: ""
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                # Specify the storage size as needed
                storage: 20Gi